export const PROOF_MODES = ["plain", "signed", "zk-placeholder", "zk"];
export const FAILURE_CODES = [
  "INVALID_INPUT","INVALID_TRUST_SCORE","INVALID_THRESHOLD","INVALID_SUBJECT","INVALID_ISSUER","EXPIRED_ATTESTATION","STALE_ATTESTATION","TRUST_BELOW_THRESHOLD","DELEGATION_EXPIRED","DELEGATION_SCOPE_VIOLATION","ROUTE_INVALID","ROUTE_TOO_LONG","ROUTE_POLICY_VIOLATION","TRANSFER_INVALID","INSUFFICIENT_SENDER_TRUST","PROOF_HASH_MISMATCH","SIGNATURE_INVALID","UNSUPPORTED_PROOF_MODE"
];
